# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-16 16:05
from __future__ import unicode_literals

from django.db import migrations, models
from django.conf import settings


def generate_operations():

    operations = []

    for code, name in settings.LANGUAGES:

        operations += [

            migrations.AddField(
                model_name='warehouse',
                name='address_%s' % code,
                field=models.CharField(db_index=True, max_length=255, null=True, verbose_name='Address'),
            ),
            migrations.AddField(
                model_name='warehouse',
                name='title_%s' % code,
                field=models.CharField(db_index=True, max_length=255, null=True, verbose_name='Title'),
            ),

        ]

        return operations

class Migration(migrations.Migration):

    dependencies = [
        ('novaposhta', '0001_initial'),
    ]

    operations = generate_operations()
